version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Easy"
    cmds:
      - protoc -I proto -I $(go env GOPATH)/pkg/mod/github.com/envoyproxy/protoc-gen-validate@v1.2.1 --go_out=paths=source_relative:./gen/chats --go-grpc_out=paths=source_relative:./gen/chats --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --validate_out="lang=go:./gen/chats" proto/*.proto
